### ISSUE TITLE
cmd-nsmgr application and testing

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/cmd-nsmgr#1]
We need to move our NSMD to new SDK and put it into new cmd-nsmgr repository.

Assigned to Alexander.

**Comment by alex-yust** [comment]
proposed functional schema:
![image](https://user-images.githubusercontent.com/54525636/77615858-efddf380-6f62-11ea-8de5-0e2b7561c58d.png)
source: https://drive.google.com/file/d/1FZniwY96QldYE2A-dQ0oZvJ5Ns3hdlKY/view?usp=sharing

**Comment by edwarnicke** [comment]
@alex-yust Have a look at:

https://github.com/networkservicemesh/sdk/pull/170

**Comment by edwarnicke** [comment]
@alex-yust Also have a look at: https://github.com/networkservicemesh/cmd-nsmgr/pull/6

**Comment by edwarnicke** [comment]
@alex-yust Also have a look at: 

https://github.com/networkservicemesh/cmd-forwarder-vppagent/pull/6
