### ISSUE TITLE
NSMgr container restarts due to concurrent map writes

### ISSUE THREAD

**Issue by alitta-german** [networkservicemesh/cmd-nsmgr#419]
We've discovered that in some cases there are several restarts of the NSMgr container. We could not filter out a single scenario for reproduction, but in most of the cases, it happened when we've installed new Endpoints (NSEs, NSCs).

my-deployment-name-nsmgr-csg65-nsmgr-prev.txt:fatal error: concurrent map writes
my-deployment-name-nsmgr-lwrl8-nsmgr-prev.txt:fatal error: concurrent map writes
my-deployment-name-nsmgr-qzrzs-nsmgr-prev.txt:panic: runtime error: invalid memory address or nil pointer dereference
my-deployment-name-nsmgr-qzrzs-nsmgr-prev.txt-[signal SIGSEGV: segmentation violation code=0x1 addr=0x1b8 pc=0x906677]
[NSMgr_logs.zip](https://github.com/networkservicemesh/cmd-nsmgr/files/7569352/NSMgr_logs.zip)

The NSMgr version that we used was 5a4b013.

**Comment by denis-tingaikin** [comment]
@alitta-german Should be fixed in the latest nsmgr. Be free to reopen this if issue is still actual.
