### ISSUE TITLE
NSE registry functionality

### ISSUE THREAD

**Issue by alex-yust** [networkservicemesh/cmd-nsmgr#5]
NSMgr must provide API for registering NSEs.
https://github.com/networkservicemesh/api/blob/master/pkg/api/registry/registry.proto

Current implementation (networkservicemesh/networkservicemesh repo) forwards all requests to a dedicated server running in k8s-nsmd container (via unix socket).

Another way can be to implement the registry in-place for simplicity sake.

**Comment by haiodo** [comment]
It is already done.
