### ISSUE TITLE
NSM_LISTEN_ON unix socket file permissions

### ISSUE THREAD

**Issue by zolug** [networkservicemesh/cmd-nsmgr#510]
This item is related to using nsm from an nsc app running as non-root.

Currently the unix listenOn socket gets created with file permissions that do not grant write access for _others_:
```
Defaulted container "nsmgr" out of: nsmgr, exclude-prefixes
/ # ls -l /var/lib/networkservicemesh/nsm.io.sock
srwxr-xr-x    1 root     root             0 Jun 28 15:01 /var/lib/networkservicemesh/nsm.io.sock
```
Since the socket gets created in a hostPath volume, nsm users mounting it can't rely for example on fsGroup to change group ownership. To workaround this, either an init container could be applied changing file permission/ownership, or CAP_DAC_OVERRIDE capability could be utilized by the _nsc binary_ to bypass permission checks.

A more user friendly approach could be setting os.ModePerm file permissions in nsmgr when the socket is created, as it would not put additional requirements on the nsc application (to run as non-root).
This behaviour would match how Spire handles _their_ unix listener:
https://github.com/spiffe/spire/blob/07219c7aed188820ebe5ffb67125fdbf69d00286/pkg/agent/endpoints/endpoints_posix.go#L31

What do you think?

nsmgr:
https://github.com/networkservicemesh/cmd-nsmgr/blob/90a32f81b77cb0f710859af51b205d1b858008ea/internal/manager/manager.go#L205
https://github.com/networkservicemesh/sdk/blob/main/pkg/tools/grpcutils/listen_and_serve.go#L66

**Comment by denis-tingaikin** [comment]
I think that its a good suggestion that can be do in v1.5.0.


@edwarnicke, @fkautz Do you have any thoughts on that?

**Comment by edwarnicke** [comment]
I think the os.ModePerm is the right solution here.

**Comment by denis-tingaikin** [comment]
Should be resovled with https://github.com/networkservicemesh/sdk/pull/1320

@zolug Feel free to reopen if we missed something.
