### ISSUE TITLE
Memory jump in high-load scenario with nsc/nse release/v1.11.2+

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/cmd-nsmgr#703]
Sometimes the memory consumption is uncontrollable increasing in the nsmgr.

Reproduced with release v1.14.0-rc.2

![image](https://github.com/user-attachments/assets/f8e2afd7-8580-4263-a460-deab10d56b46)

**Comment by szvincze** [comment]
We tested with custom clients and endpoints that used SDK v1.13.2 where we observed the above described behavior.
One time we tried to let the `nsmgr`s reach the memory limit and to be restarted. Surprisingly, after the `nsmgr` processes were OOMKilled then came up properly and did not show any significant increase of memory consumption. On this picture the restarts happened at 0:00 and 05:00.

![Screenshot from 2024-09-23 08-37-31](https://github.com/user-attachments/assets/53023fee-5448-4fbb-b2ca-9b9f56ef05e6)

After that we also tried to restart `nsmgr` manually to see if it had effect on the increasing memory consumption. We restarted `nsmgr`s in different ways in the different tests to see if the restart method matters, but haven't seen difference when we killed the process or deleted the pod etc, it always flattened the memory diagram.

Here I add some more pictures we took during our tests.
![nsmgr-memory-after-restart-1](https://github.com/user-attachments/assets/b0cd0861-50fa-4e69-9ff3-9130b6ca6a56)

![Screenshot from 2024-09-23 08-36-34](https://github.com/user-attachments/assets/0fa41b9a-0d69-4147-91bd-5c7733a1e69c)

![Screenshot from 2024-09-23 08-35-59](https://github.com/user-attachments/assets/7f1eb38b-a90f-4abf-b48d-2bd65a08f68c)

![Screenshot from 2024-09-23 08-35-14](https://github.com/user-attachments/assets/456e172e-c555-49e8-83da-0f72d43ef7d9)

![Screenshot from 2024-09-23 08-34-43](https://github.com/user-attachments/assets/39cc2603-ff14-40b9-9385-ad20377ad146)

Each test showed the same behavior. For some reason the restart of `nsmgr` completely eliminated the memory increase.

This last one shows the test when we let the system continue to run after the restart to see if it starts growing some time later but nothing suspicious happened for more that 11 hours:
![Screenshot from 2024-09-23 08-34-00](https://github.com/user-attachments/assets/6b737bdc-5707-4c8c-8a91-0e62326da199)

Do you have any idea what could cause this behavior?

**Comment by denis-tingaikin** [comment]
> Do you have any idea what could cause this behavior?

My guess the problem is in the diff in the nsc from v1.11.2 to main. Most likely, monitor streams are not closing. Currently, I am working with quick reproduction; I will inform you when we get more information.

**Comment by szvincze** [comment]
> > Do you have any idea what could cause this behavior?
> 
> My guess the problem is in the diff in the nsc from v1.11.2 to main. Most likely, monitor streams are not closing. Currently, I am working with quick reproduction; I will inform you when we get more information.

Would it be an explanation why the memory graph flattens after restarting `nsmgr`?

**Comment by szvincze** [comment]
Just a small addition. It seems when we stop the test and delete the respective test namespace `nsmgr` gives back the memory it leaked, which was not the case previously.
![Screenshot from 2024-09-24 11-54-18](https://github.com/user-attachments/assets/ca36c921-bb65-41fd-8967-89ce62c92300)

**Comment by zolug** [comment]
Hi @denis-tingaikin,

The NSC used in Meridio: https://github.com/Nordix/Meridio/blob/master/cmd/proxy/main.go#L243
(There's another NSC as well, but the memory increase is visible when using only the NSC above.)

Simply on a Kind cluster I also noticed the differences Szilard reported (by leaving the cluster intact without any traffic). 

Meridio 1.1.1
![Screenshot from 2024-10-01 17-48-16](https://github.com/user-attachments/assets/898699be-f929-4559-bf5b-6859f4b36424)


Meridio 1.1.2
![Screenshot from 2024-10-01 13-29-58](https://github.com/user-attachments/assets/d10bbe07-0f7d-46bb-aa8b-81e588e9f7f5)

**Comment by denis-tingaikin** [comment]
Hello @zolug,

I mentioned this problem: https://github.com/networkservicemesh/cmd-nsmgr/issues/675 on the last call. The problem actually can be on the client side. At this moment we're avoiding it on the server side, which can be not a perfect solution. Currently planned to have a look a bit deeply into code on the client side.

**Comment by denis-tingaikin** [comment]
@szvincze Could we test docker pull ghcr.io/networkservicemesh/ci/cmd-nsmgr:d1e85e8 when you get a time?

**Comment by denis-tingaikin** [comment]
It looks good; it seems like we are already able to get rid of using workarounds in the next releases. Let's keep the open this ticket till next RC.

**Comment by NikitaSkrynnik** [comment]
Hello, @szvincze! Could you tell please if you used scaling of clients and endpoints in this test: https://github.com/networkservicemesh/cmd-nsmgr/issues/703#issuecomment-2464240176

cc @edwarnicke

**Comment by szvincze** [comment]
Hi @NikitaSkrynnik,  In this test we don't scale clients and endpoints. In the beginning we balance the connections but after that the deployment is static.

**Comment by denis-tingaikin** [comment]
@szvincze Previously we reproduced all problems with a high-load dynamic environment. Seems like static env was used because previously you found a problem with the client's monitor services, right?

**Comment by szvincze** [comment]
Hi @denis-tingaikin,  yes, we also tested with dynamic environments too because it was easier/faster to reproduce the different leaks we found. In this environment we test with a quite static setup on a high load.

**Comment by denis-tingaikin** [comment]
It was not reproduced with latest release , so looks like done.
