### ISSUE TITLE
Connectivity changes during runtime

### ISSUE THREAD

**Issue by abhiranjeet** [networkservicemesh/cmd-nsmgr#89]
Hi ! I have a question : 

- Lets say I have 9 containers running in a cluster which comprise of a Network Service. 

- Now after some time, I want to add a new container which needs to connect to my other 9 containers running previously. 

- How does NSM address connectivity during runtime when new containers are included in the network service ?

Thanks in advance !

**Comment by edwarnicke** [comment]
@abhiranjeet Let me make sure I understand your question:

When you say
> Lets say I have 9 containers running in a cluster which comprise of a Network Service.

Do you mean you have 9 Pods which are *Network Service Clients(NSCs)* of a particular Network Service?

or 

Do you mean you have 9Pods which are Network Service Endpoints (NSEs) composed together to *provide* the Network Service?

**Comment by abhiranjeet** [comment]
Sorry for not being clear about this :

- I mean 9 pods which are NSEs composed together to provide the Network Service.

Thanks

**Comment by barby1138** [comment]
Hi
Did we have any conclusion here.
I also have question how I can recompose NSEs in runtime without redeployment of existing modules?
Lets take the simple case.
with NSC:
lets say I had NSC1->NSE1 NSC2->NSE2
now I want both NSC1->NSE1 NSC2->NSE1

NSE1 and NSE2 represent same networkservice

thanks

**Comment by glazychev-art** [comment]
Hi @barby1138 ,
I'm not sure if this is a valid case... A particular NSE implements a certain networkservice. NSC requests the service for its functionality.
If NSE1 and NSE2 represent same networkservice then no difference what to connect to.
